-- IRIS Blueprint — Database Schema
-- PostgreSQL 16+ with pgcrypto and uuid-ossp extensions
--
-- This schema defines the core tables for an AI executive assistant.
-- All tables are designed for a single-user system. Multi-tenant
-- adaptation would require adding user_id columns and RLS policies.

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- OPERATIONAL STATE — Persistent whiteboard (survives crashes)
-- ============================================================

CREATE TABLE operational_state (
  id         SERIAL PRIMARY KEY,
  key        TEXT NOT NULL UNIQUE,
  value      JSONB NOT NULL,
  updated_at TIMESTAMP DEFAULT now(),
  updated_by TEXT DEFAULT 'IRIS'
);

COMMENT ON TABLE operational_state IS 'Persistent key-value whiteboard. The assistant reads this on startup to restore context.';
COMMENT ON COLUMN operational_state.key IS 'Unique key name (top6, pending_tomorrow, blockers, session_notes, session_texture, active_narratives, etc)';
COMMENT ON COLUMN operational_state.value IS 'JSONB payload. Structure varies by key.';
COMMENT ON COLUMN operational_state.updated_at IS 'Last write timestamp. Check this to know freshness.';

-- Seed standard keys
INSERT INTO operational_state (key, value) VALUES
  ('top6', '{"date": null, "items": []}'),
  ('pending_tomorrow', '{"date": null, "items": [], "committed": false}'),
  ('blockers', '[]'),
  ('session_notes', '{}'),
  ('session_texture', '{}'),
  ('active_narratives', '{}'),
  ('last_closeout', '{}');


-- ============================================================
-- SESSIONS — Session registry
-- ============================================================

CREATE TABLE sessions (
  session_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  role              VARCHAR(20) NOT NULL DEFAULT 'primary',
  started_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_heartbeat    TIMESTAMPTZ NOT NULL DEFAULT now(),
  status            VARCHAR(20) NOT NULL DEFAULT 'active',
  shutdown_type     VARCHAR(20),
  notes             TEXT,
  assigned_channels TEXT[],
  persona           VARCHAR(30),
  config            JSONB DEFAULT '{}'
);

COMMENT ON TABLE sessions IS 'Registry of assistant sessions. Tracks start time, status, assigned channels.';


-- ============================================================
-- MESSAGE SYSTEM — Conversation logging and routing
-- ============================================================

CREATE TABLE message_log (
  id           SERIAL PRIMARY KEY,
  channel      TEXT NOT NULL,
  sender       TEXT NOT NULL,
  message_text TEXT NOT NULL,
  message_type TEXT DEFAULT 'text',
  persona      TEXT,
  timestamp    TIMESTAMPTZ DEFAULT now(),
  session_id   TEXT,
  embedded     BOOLEAN DEFAULT false
);

COMMENT ON TABLE message_log IS 'Raw conversation log. 2-week retention. Nightly embedding compresses to vector DB.';
COMMENT ON COLUMN message_log.channel IS 'Channel name: DM, Professional, Coaching, etc.';
COMMENT ON COLUMN message_log.sender IS 'Who sent: user name for inbound, persona name for outbound';
COMMENT ON COLUMN message_log.embedded IS 'Whether this message has been embedded to the vector DB. false=pending, true=done.';

CREATE INDEX idx_message_log_channel_ts ON message_log (channel, timestamp DESC);
CREATE INDEX idx_message_log_embedded ON message_log (embedded) WHERE embedded = false;


CREATE TABLE channel_routing (
  chat_id      BIGINT PRIMARY KEY,
  channel_name VARCHAR(30) NOT NULL,
  persona      VARCHAR(30) NOT NULL,
  session_id   UUID,
  is_forum     BOOLEAN DEFAULT false,
  notes        TEXT
);

COMMENT ON TABLE channel_routing IS 'Maps chat platform IDs to channel names and personas.';


CREATE TABLE forum_topics (
  id         SERIAL PRIMARY KEY,
  chat_id    VARCHAR(30) NOT NULL,
  topic_id   INTEGER NOT NULL,
  topic_name VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (chat_id, topic_id)
);

COMMENT ON TABLE forum_topics IS 'Forum topic directory. Loaded at startup for message routing.';


CREATE TABLE conversation_summaries (
  id              SERIAL PRIMARY KEY,
  channel         TEXT NOT NULL,
  persona         TEXT,
  summary         TEXT NOT NULL,
  topics          TEXT[],
  emotional_tone  TEXT,
  decisions_made  TEXT[],
  action_items    TEXT[],
  message_count   INTEGER,
  first_message_at TIMESTAMPTZ,
  last_message_at  TIMESTAMPTZ,
  qdrant_point_id INTEGER,
  created_at      TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE conversation_summaries IS 'Compressed conversation summaries generated by the nightly embedding pipeline.';


CREATE TABLE message_inbox (
  id                   SERIAL PRIMARY KEY,
  chat_id              BIGINT NOT NULL,
  message_id           BIGINT,
  sender_name          TEXT,
  sender_id            BIGINT,
  message_text         TEXT,
  media_path           TEXT,
  reply_to_message_id  BIGINT,
  topic_id             INTEGER,
  channel              VARCHAR(30),
  target_session       UUID,
  status               VARCHAR(20) DEFAULT 'pending',
  created_at           TIMESTAMPTZ DEFAULT now(),
  claimed_at           TIMESTAMPTZ,
  claimed_by           UUID
);

COMMENT ON TABLE message_inbox IS 'Inbound message queue. Messages land here before being claimed by a session.';


CREATE TABLE message_outbox (
  id                   SERIAL PRIMARY KEY,
  chat_id              BIGINT NOT NULL,
  message_text         TEXT,
  reply_to_message_id  BIGINT,
  topic_id             INTEGER,
  files                TEXT[],
  parse_mode           VARCHAR(20),
  channel              VARCHAR(30),
  persona              VARCHAR(30),
  source_session       UUID,
  status               VARCHAR(20) DEFAULT 'pending',
  created_at           TIMESTAMPTZ DEFAULT now(),
  sent_at              TIMESTAMPTZ,
  sent_message_id      BIGINT,
  error                TEXT
);

COMMENT ON TABLE message_outbox IS 'Outbound message queue. Crons or sessions write here; a delivery process sends.';


-- ============================================================
-- TASK MANAGEMENT
-- ============================================================

CREATE TABLE work_list (
  id            SERIAL PRIMARY KEY,
  system        VARCHAR(20) NOT NULL,
  category      VARCHAR(20) NOT NULL,
  title         TEXT NOT NULL,
  description   TEXT,
  priority      INTEGER DEFAULT 3,
  status        VARCHAR(20) DEFAULT 'open',
  due_date      DATE,
  created_at    TIMESTAMPTZ DEFAULT now(),
  completed_at  TIMESTAMPTZ,
  created_by    VARCHAR(50) DEFAULT 'assistant',
  person        TEXT,
  shift         TEXT DEFAULT 'day',
  scheduled_date DATE,
  blocked_by    INTEGER REFERENCES work_list(id),
  updated_at    TIMESTAMPTZ DEFAULT now(),
  manifest_path TEXT
);

COMMENT ON TABLE work_list IS 'Central work tracking. Items with shift=night and manifest_path are eligible for overnight autonomous execution.';
COMMENT ON COLUMN work_list.system IS 'Which system owns this work item';
COMMENT ON COLUMN work_list.priority IS '1=highest, 4=lowest';
COMMENT ON COLUMN work_list.status IS 'open, in_progress, testing (needs review), done, killed';
COMMENT ON COLUMN work_list.shift IS 'day or night. Night items are worked during overnight crons.';
COMMENT ON COLUMN work_list.manifest_path IS 'Path to work manifest file with instructions and acceptance criteria.';

-- Auto-update trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER work_list_updated_at
  BEFORE UPDATE ON work_list
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();


CREATE TABLE gok_tasks (
  id            SERIAL PRIMARY KEY,
  title         TEXT NOT NULL,
  description   TEXT,
  category      VARCHAR(30) DEFAULT 'general',
  priority      INTEGER DEFAULT 3,
  status        VARCHAR(20) DEFAULT 'open',
  created_at    TIMESTAMPTZ DEFAULT now(),
  completed_at  TIMESTAMPTZ,
  resurface_date DATE
);

COMMENT ON TABLE gok_tasks IS 'Gap-of-knowledge tasks for idle time. Low-priority learning and exploration.';
COMMENT ON COLUMN gok_tasks.title IS 'Task title for gap-of-knowledge or idle time work';
COMMENT ON COLUMN gok_tasks.priority IS '1=highest, 4=lowest';
COMMENT ON COLUMN gok_tasks.status IS 'open, done, killed, moved (to work_list)';


CREATE TABLE etool (
  id                SERIAL PRIMARY KEY,
  task              TEXT NOT NULL,
  description       TEXT,
  quadrant          INTEGER NOT NULL,
  original_quadrant INTEGER NOT NULL,
  decay_days        INTEGER DEFAULT 14,
  created_at        TIMESTAMP DEFAULT now(),
  escalation_date   TIMESTAMP,
  status            TEXT DEFAULT 'active',
  assigned_to       TEXT DEFAULT 'assistant',
  channel           TEXT,
  updated_at        TIMESTAMP DEFAULT now()
);

COMMENT ON TABLE etool IS 'Eisenhower matrix with automatic Q2-to-Q1 decay. Tasks escalate after decay_days.';


CREATE TABLE personal_tasks (
  id           SERIAL PRIMARY KEY,
  title        TEXT NOT NULL,
  due_date     DATE,
  category     TEXT DEFAULT 'errand',
  priority     INTEGER DEFAULT 2,
  status       TEXT DEFAULT 'open',
  person       TEXT,
  created_at   TIMESTAMP DEFAULT now(),
  completed_at TIMESTAMP,
  source       TEXT DEFAULT 'chat'
);

COMMENT ON TABLE personal_tasks IS 'Personal to-do items. Lighter weight than work_list.';


CREATE TABLE iris_inbox (
  id             SERIAL PRIMARY KEY,
  type           TEXT NOT NULL DEFAULT 'thought',
  raw_text       TEXT NOT NULL,
  source         TEXT DEFAULT 'text',
  source_channel TEXT,
  captured_at    TIMESTAMPTZ DEFAULT now(),
  triaged        BOOLEAN DEFAULT false,
  triaged_at     TIMESTAMPTZ,
  disposition    TEXT,
  routed_to      TEXT,
  routed_id      INTEGER,
  notes          TEXT
);

COMMENT ON TABLE iris_inbox IS 'GTD capture inbox. Raw thoughts and tasks captured with zero friction.';
COMMENT ON COLUMN iris_inbox.type IS 'thought or task';
COMMENT ON COLUMN iris_inbox.raw_text IS 'Exact verbatim text. Never edited after capture.';
COMMENT ON COLUMN iris_inbox.triaged IS 'false=needs triage. true=has been routed/killed/deferred.';
COMMENT ON COLUMN iris_inbox.disposition IS 'Where it went: routed, killed, deferred, embedded';


-- ============================================================
-- KNOWLEDGE & CONTENT
-- ============================================================

CREATE TABLE content_ideas (
  id           SERIAL PRIMARY KEY,
  title        TEXT NOT NULL,
  description  TEXT,
  category     VARCHAR(50) DEFAULT 'general',
  status       VARCHAR(20) DEFAULT 'idea',
  priority     INTEGER DEFAULT 3,
  created_at   TIMESTAMPTZ DEFAULT now(),
  published_at TIMESTAMPTZ
);

COMMENT ON TABLE content_ideas IS 'Content pipeline ideas. Captured from conversations, research, or brainstorming.';


CREATE TABLE decision_log (
  id         SERIAL PRIMARY KEY,
  date       DATE DEFAULT CURRENT_DATE,
  decision   TEXT NOT NULL,
  why        TEXT NOT NULL,
  context    TEXT,
  reversible BOOLEAN DEFAULT true,
  created_by TEXT DEFAULT 'assistant'
);

COMMENT ON TABLE decision_log IS 'Record of significant decisions with rationale.';


-- ============================================================
-- SYSTEM TABLES
-- ============================================================

CREATE TABLE secrets (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name            TEXT NOT NULL UNIQUE,
  service         TEXT NOT NULL,
  encrypted_value BYTEA NOT NULL,
  description     TEXT,
  rotated_at      TIMESTAMPTZ DEFAULT now(),
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE secrets IS 'Encrypted secrets vault. All API keys stored here with pgcrypto.';
COMMENT ON COLUMN secrets.name IS 'Unique key name (e.g., anthropic_api_key, telegram_bot_token)';
COMMENT ON COLUMN secrets.encrypted_value IS 'Encrypted with pgcrypto. Decrypt: decrypt_secret(encrypted_value, passphrase)';
COMMENT ON COLUMN secrets.rotated_at IS 'When this key was last rotated. Flag if older than 90 days.';


CREATE TABLE skill_registry (
  id              SERIAL PRIMARY KEY,
  name            TEXT NOT NULL UNIQUE,
  domain          TEXT NOT NULL,
  description     TEXT,
  version         TEXT DEFAULT 'v1',
  status          TEXT DEFAULT 'active',
  playbook        JSONB DEFAULT '{}',
  lessons_learned JSONB DEFAULT '[]',
  metrics         JSONB DEFAULT '{}',
  productizable   BOOLEAN DEFAULT false,
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE skill_registry IS 'Registry of assistant capabilities with version tracking and lessons learned.';


CREATE TABLE night_work_runs (
  id            SERIAL PRIMARY KEY,
  run_date      DATE NOT NULL DEFAULT CURRENT_DATE,
  phase         TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'running',
  summary       TEXT,
  output        JSONB DEFAULT '{}',
  started_at    TIMESTAMPTZ DEFAULT now(),
  completed_at  TIMESTAMPTZ,
  duration_ms   INTEGER,
  error_message TEXT
);

COMMENT ON TABLE night_work_runs IS 'Observability log for overnight autonomous work phases.';
COMMENT ON COLUMN night_work_runs.phase IS 'Which phase: engine, research, synthesis, maintenance, git_backup, intelligence_brief';
COMMENT ON COLUMN night_work_runs.status IS 'running, completed, failed, skipped';
COMMENT ON COLUMN night_work_runs.output IS 'Structured output: items processed, findings, recommendations';


CREATE TABLE startup_manifest (
  id           SERIAL PRIMARY KEY,
  category     TEXT NOT NULL,
  name         TEXT NOT NULL,
  description  TEXT,
  pointer      TEXT,
  verification TEXT,
  active       BOOLEAN DEFAULT true,
  updated_at   TIMESTAMP DEFAULT now()
);

COMMENT ON TABLE startup_manifest IS 'Startup checklist items. Defines what gets loaded during session boot.';


CREATE TABLE closeout_checklist (
  id           SERIAL PRIMARY KEY,
  session_id   TEXT NOT NULL,
  step         TEXT NOT NULL,
  description  TEXT,
  completed    BOOLEAN DEFAULT false,
  completed_at TIMESTAMPTZ,
  created_at   TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE closeout_checklist IS 'Session closeout tracking. Ensures no steps are skipped.';


CREATE TABLE iris_calendar (
  id            SERIAL PRIMARY KEY,
  title         TEXT NOT NULL,
  description   TEXT,
  start_time    TIMESTAMPTZ NOT NULL,
  end_time      TIMESTAMPTZ,
  all_day       BOOLEAN DEFAULT false,
  channel       TEXT,
  persona       TEXT,
  event_type    TEXT DEFAULT 'event',
  recurring     TEXT,
  reminder_sent BOOLEAN DEFAULT false,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE iris_calendar IS 'Internal calendar for assistant-managed events. Separate from Google Calendar.';


CREATE TABLE iris_corrections (
  id              SERIAL PRIMARY KEY,
  channel         TEXT,
  context         TEXT,
  what_iris_said  TEXT,
  what_josh_said  TEXT,
  correction_type TEXT DEFAULT 'factual',
  applied         BOOLEAN DEFAULT false,
  created_at      TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE iris_corrections IS 'Tracks every user correction. Audit trail for behavioral improvement.';
COMMENT ON COLUMN iris_corrections.context IS 'What was being discussed when the correction happened';
COMMENT ON COLUMN iris_corrections.what_iris_said IS 'What the assistant got wrong';
COMMENT ON COLUMN iris_corrections.what_josh_said IS 'What the user said to correct it';
COMMENT ON COLUMN iris_corrections.correction_type IS 'factual, behavioral, formatting, or process';
COMMENT ON COLUMN iris_corrections.applied IS 'Whether the correction was persisted to memory/skills/config';


CREATE TABLE deploys (
  id            SERIAL PRIMARY KEY,
  engine        TEXT NOT NULL,
  commit_hash   TEXT,
  message       TEXT,
  files_changed INTEGER,
  deployed_at   TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE deploys IS 'Deploy history for all managed services.';


-- ============================================================
-- CONVENIENCE FUNCTION — Secret decryption
-- ============================================================

CREATE OR REPLACE FUNCTION decrypt_secret(val BYTEA, pass TEXT)
RETURNS TEXT AS $$
  SELECT pgp_sym_decrypt(val, pass);
$$ LANGUAGE SQL;
